# Generated by Django 3.0.8 on 2020-08-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
