# Generated by Django 3.0.8 on 2020-08-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_blog', '0002_auto_20200806_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('date',)},
        ),
    ]
