# Generated by Django 3.0.8 on 2021-02-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_blog', '0004_auto_20200806_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
