# Generated by Django 3.0.8 on 2020-07-17 03:22

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=False)]},
        ),
    ]
