# Generated by Django 3.0.8 on 2020-07-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_skills', '0002_auto_20200717_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id']},
        ),
    ]
