# Generated by Django 3.0.8 on 2020-07-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_skills', '0003_auto_20200717_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Language',
        ),
    ]
