# Generated by Django 3.0.8 on 2020-07-19 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
