# Generated by Django 3.0.8 on 2020-07-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_projects', '0002_auto_20200719_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='class_name',
            field=models.CharField(default='col-lg-3 col-md-4 portfolio-item isotope-item', max_length=150),
        ),
    ]
